- name: Check Existing PKI Files and Directories
  stat:
    path: "{{ OVPN_VOLUME_PATH }}/{{ item }}"
  loop:
    - pki
    - pki/private
    - pki/reqs
    - pki/ca.crt
    - pki/private/ca.key
    - pki/index.txt
    - pki/index.txt.attr
    - pki/serial
  register: ca_stats

- name: Set fact for missing files/directories
  set_fact:
    missing_files: "{{ ca_stats.results | selectattr('stat.exists', 'equalto', false) | list }}"
  
- name: Display Missing Files and Directories
  debug:
    msg: "File/directory '{{ item.item }}' is missing."
  loop: "{{ missing_files }}"
  loop_control:
    label: "{{ item.item }}"

- name: Generate PKI Files and OpenVPN Configuration (Skip If Existing)
  when: OVPN_OVERRIDE_EXISTING_CA or missing_files | length > 0
  block:
    - name: Create temporary file for PKI generation
      tempfile:
        state: file
      register: temp_file

    - name: Generate PKI and OpenVPN configuration
      template:
        src: setup.sh.j2
        dest: "{{ temp_file.path }}"
        mode: "0755"
    
    - name: Execute PKI generation script
      command: "{{ temp_file.path }}"
